### PR TITLE
dev-libs/aml: Increment to 0.2.1 from 0.1.0

### PR DESCRIPTION
**Pull request by Archetypic**
* Add option `examples`

### CODE REVIEW

**Comment by Archetypic** [comment]
Despite using `git mv`, Github portrays it as deleting file `0.1.0` and creating file `0.2.1`.

How do I avoid this inconsistency?

**Comment by Archetypic** [comment]
Binaries for examples are compiled as well, merely excluded from installation.

**Comment by Archetypic** [comment]
> Despite using `git mv`, Github portrays it as deleting file `0.1.0` and creating file `0.2.1`.
> 
> How do I avoid this inconsistency?

My apologies, this is a personal issue.

**Comment by ony** [comment]
@Archetypic , thank you for your contribution and sorry for delay.

Please consider adopting this library to your own repo and whatever package you wanted it to be updated for.

**Pull request merged**
